# Generated by Django 2.0.1 on 2018-01-19 23:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('idO', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('howMuch', models.DecimalField(decimal_places=0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Zamówienie',
            fields=[
                ('idK', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.TimeField(verbose_name=datetime.datetime(2018, 1, 19, 23, 16, 51, 795644, tzinfo=utc))),
                ('id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RedPepper.Oferta')),
            ],
        ),
    ]
