# Generated by Django 2.0.1 on 2018-01-20 00:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RedPepper', '0002_auto_20180120_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamówienie',
            name='id',
        ),
        migrations.AddField(
            model_name='zamówienie',
            name='zamowienia',
            field=models.ManyToManyField(to='RedPepper.Oferta'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='zamówienie',
            name='created_date',
            field=models.TimeField(verbose_name=datetime.datetime(2018, 1, 20, 0, 8, 24, 799986, tzinfo=utc)),
        ),
    ]
