# Generated by Django 2.0.1 on 2018-01-20 00:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RedPepper', '0007_auto_20180120_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('idK', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Platnosc',
            fields=[
                ('idP', models.AutoField(primary_key=True, serialize=False)),
                ('rodzaj', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='zamówienie',
            name='created_date',
            field=models.TimeField(verbose_name=datetime.datetime(2018, 1, 20, 0, 37, 41, 194391, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='zamówienie',
            name='klient',
            field=models.ManyToManyField(to='RedPepper.Klient'),
        ),
    ]
