# Generated by Django 2.0.1 on 2018-01-20 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RedPepper', '0008_auto_20180120_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamówienie',
            name='Platnosc',
            field=models.ManyToManyField(to='RedPepper.Platnosc'),
        ),
        migrations.AlterField(
            model_name='zamówienie',
            name='created_date',
            field=models.TimeField(verbose_name=datetime.datetime(2018, 1, 20, 0, 39, 21, 921329, tzinfo=utc)),
        ),
    ]
