# Generated by Django 2.0.1 on 2018-01-20 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RedPepper', '0010_auto_20180120_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamówienie',
            name='created_date',
            field=models.TimeField(verbose_name=datetime.datetime(2018, 1, 20, 11, 16, 2, 164987, tzinfo=utc)),
        ),
    ]
