# Generated by Django 2.0.1 on 2018-01-20 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RedPepper', '0012_auto_20180120_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='info',
            field=models.ManyToManyField(null=True, to='RedPepper.Skladniki'),
        ),
        migrations.AlterField(
            model_name='zamówienie',
            name='created_date',
            field=models.TimeField(verbose_name=datetime.datetime(2018, 1, 20, 13, 1, 20, 687559, tzinfo=utc)),
        ),
    ]
