# Generated by Django 2.0.1 on 2018-01-20 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RedPepper', '0013_auto_20180120_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='info',
            field=models.ManyToManyField(to='RedPepper.Skladniki'),
        ),
        migrations.AlterField(
            model_name='zamówienie',
            name='created_date',
            field=models.TimeField(verbose_name=datetime.datetime(2018, 1, 20, 13, 3, 16, 678265, tzinfo=utc)),
        ),
    ]
